name: My-brand CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [ dev ]
env: 
  MONGO_URL_TEST_ONLINE: ${{ secrets.MONGO_URL_TEST_ONLINE }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
  CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
  CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run coverage
    - run: npm run build --if-present
